require("plugins-setup")
require("options")
require("my_plugins.nvim-cmp")
require("my_plugins.mason")
require("my_plugins.telescope")
require("my_plugins.treesitter")
require("my_plugins.gitsigns")
require("my_plugins.nvim-tree")
